server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # A mágica do React Router acontece aqui.
        # Tenta achar o arquivo ($uri), depois a pasta ($uri/), 
        # e se não achar nenhum dos dois, manda para o index.html.
        try_files $uri $uri/ /index.html;
    }
}